### PR TITLE
Merge pull request #7 from yuchenlin/master

### PR DESCRIPTION
**Pull request by yuchenlin**
More Optimizers, Clip, Reload and A more flexible data reading method

### CODE REVIEW

**Comment by sgudur** [comment]
Class CoNLLDataset isnt working, it doesn't throw a tuple of sentence and tag

**Comment by yuchenlin** [comment]
@sgudur I'm sorry. Could you please provide more details? like the config and the input format?

**Comment by sgudur** [comment]
Sure, in data_utils.py file the itreable CoNLLDataset(object):
For method  def __iter__(self):

The last two lines are missing,

Yield word, tag
return self

was missing. I tried to use this code and couldn’t find any return values When I used build_data.py file

Following lines give no result.
    # Generators
    dev   = CoNLLDataset(config.dev_filename, processing_word)
    test  = CoNLLDataset(config.test_filename, processing_word)
    train = CoNLLDataset(config.train_filename, processing_word)

after adding those two lines the code worked and it gave me dev, test, train data sets

**Comment by yuchenlin** [comment]
Hi Shashi, 

Sorry for the inconvenience. I am not sure about the exact reason, because the current code works fine with me using conll-format datasets and I actually did not modify this part from the original repo. I guess you are using a different dataset? (since now the ``yield'' step is after the detection of a blank line or a line with ''DOCSTART'')

Anyway, it's good to see that the code works for you now after adding the two lines.

**Pull request merged**
